version: "3.3"
services:
  crawlerapi:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: "crawlerapi"
    env_file: .env
    ports:
      - "5050:5050"
    volumes:
      - type: bind
        source: .
        target: /app
    command: uwsgi --ini=uwsgi.ini --workers=1
    depends_on:
      - db
  db:
    image: "postgres:12.3"
    container_name: "db"
    environment:
      POSTGRES_DB: "zameen_data"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data
    command: -p 5432
  prometheus:
    image: "prom/prometheus"
    container_name: "real_estate_prometheus"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/local_prometheus.yml:/etc/prometheus/prometheus.yml
  pushgateway:
    image: "prom/pushgateway"
    container_name: "real_estate_pushgateway"
    ports:
      - "9091:9091"
  grafana:
    image: grafana/grafana
    container_name: "real_estate_grafana"
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  db_volume:
