# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15s.
  evaluation_interval: 1m # Evaluate rules every 1m. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly two endpoints to scrape:
# - the Docker container hosting Prometheus
# - the host machine running the API server
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "api_server"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["crawlerapi:5050"]
  - job_name: "pushgateway"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    # set "honor_labels" to true, so that labels in incoming data will override
    # the labels that pushmetrics auto-generates
    honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]
